### PR TITLE
Allow only elm 0.19 operators

### PR DESCRIPTION
**Pull request by brianvanburken**
I took a stab at issue #3. I've split up the operator regex based on the elm packages

### CODE REVIEW

**Comment by andys8** [comment]
Nice, dif you do some research if this is a complete list?

**Comment by andys8** [comment]
It looks complete to me.

https://github.com/search?p=1&q=infix+user%3Aelm+user%3Aevancz+user%3Aelm-explorations&type=Code&utf8=%E2%9C%93

**Comment by brianvanburken** [comment]
I did the same lookup @andys8 posted and a manual review of all the packages that are allowed to have infix operators (elm & elm-explorations)

**Comment by andys8** [comment]
Thanks :)

**Pull request merged**
